### ISSUE TITLE
Souvenir abandons Rainbow Arrows and Stellar

### ISSUE THREAD

**Issue by TachUDF** [Timwi/KtaneSouvenir#116]
Souvenir abandons Rainbow Arrows and Stellar, I took some from Filtered Log:

Rainbow Arrows:
`‹Souvenir #1› Module ksmRainbowArrows: Start processing.`
`<Souvenir #1> Abandoning Rainbow Arrows because: ksmRainbowArrows(Clone) game object has no ksmRainbowArrows component. Components are: UnityEngine.Transform, KMSelectable, KMBombInfo, KMAudio, KMBombModule, RainbowArrows, ModSource, ModSelectable, ModBombInfo, ModAudio, ModBombComponent, ExcludeFromStaticBatch`

Stellar:
`‹Souvenir #1› Module stellar: Start processing.`
`<Souvenir #1> Abandoning Stellar because: Type StellarScript does not contain public property IsSolved. Properties are: public System.Boolean useGUILayout, public System.Boolean enabled, public System.Boolean isActiveAndEnabled, public UnityEngine.Transform transform, public UnityEngine.GameObject gameObject, public System.String tag, public System.String name, public UnityEngine.HideFlags hideFlags`

**Comment by TheKuroEver** [comment]
I'll have a look. Next time, please ping Timwi (or, ideally, whoever implemented support for the module(s) in question, which you can find [here](https://github.com/Timwi/KtaneSouvenir/blob/master/CONTRIBUTORS.md) in the mod bug reports channel on the official KTANE discord, since I'm pretty sure Timwi does not receive notifications about this, and other contributors like me certainly don't. @TachUDF

**Comment by TheKuroEver** [comment]
Should be fixed once [my commit](https://github.com/TheKuroEver/KtaneSouvenir/commit/fdfa10612a95d134deec1a37f1042768d8e4bbe6) is merged.
